name: Build Tauri App
run: |
  cd frontend
  npm run tauri build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Python (for backend)
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Build Tauri App
        run: |
          cd frontend
          npm run tauri build

      - name: Upload artifacts (optional, still accessible in Actions tab)
        uses: actions/upload-artifact@v4
        with:
          name: tauri-build-${{ matrix.platform }}
          path: frontend/src-tauri/target/release/bundle/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/heads/main')
        with:
          tag_name: v${{ github.run_number }}
          name: "Tauri Build ${{ github.run_number }}"
          body: "Automated release of Tauri desktop builds."
          files: |
            frontend/src-tauri/target/release/bundle/**/*.exe
            frontend/src-tauri/target/release/bundle/**/*.dmg
            frontend/src-tauri/target/release/bundle/**/*.AppImage
        env:
          GITHUB_TOKEN: $_
