name: Build Tauri App

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Python (for backend)
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Build Tauri App
        run: |
          cd frontend
          npm run tauri build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: tauri-build-${{ matrix.platform }}
          path: frontend/src-tauri/target/release/bundle/
